# Build and push image to Azure Container Registry, then publish artifacts

trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '04c6fc8e-8837-4245-b1a3-1b37c657e73a'
  imageRepository: 'nginix2deplyoartifact'
  containerRegistry: 'aksdemo2acr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'aksdemo2acr8831513c-auth'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build and push
    pool:
      name: 'ubuntu-selhosted'  # self-hosted agent
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: PublishPipelineArtifact@1
      displayName: 'Publish manifests artifact'
      inputs:
        targetPath: 'manifests'          # folder you want to publish
        artifact: 'manifests'            # name of the artifact in release pipeline
        publishLocation: 'pipeline'
